import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          glow: "hsl(var(--primary-glow))",
          light: "hsl(var(--primary-light))",
          dark: "hsl(var(--primary-dark))",
          5: "hsl(var(--primary) / 0.05)",
          10: "hsl(var(--primary) / 0.1)",
          12: "hsl(var(--primary) / 0.12)",
          15: "hsl(var(--primary) / 0.15)",
          20: "hsl(var(--primary) / 0.2)",
          25: "hsl(var(--primary) / 0.25)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          light: "hsl(var(--accent-light))",
          5: "hsl(var(--accent) / 0.05)",
          8: "hsl(var(--accent) / 0.08)",
          10: "hsl(var(--accent) / 0.1)",
          12: "hsl(var(--accent) / 0.12)",
          15: "hsl(var(--accent) / 0.15)",
          20: "hsl(var(--accent) / 0.2)",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
          5: "hsl(var(--warning) / 0.05)",
          10: "hsl(var(--warning) / 0.1)",
          12: "hsl(var(--warning) / 0.12)",
          15: "hsl(var(--warning) / 0.15)",
          20: "hsl(var(--warning) / 0.2)",
          25: "hsl(var(--warning) / 0.25)",
          50: "hsl(var(--warning) / 0.05)",
          100: "hsl(var(--warning) / 0.1)",
          200: "hsl(var(--warning) / 0.2)",
          300: "hsl(var(--warning) / 0.3)",
          400: "hsl(var(--warning) / 0.4)",
          500: "hsl(var(--warning) / 0.5)",
          600: "hsl(var(--warning) / 0.6)",
          700: "hsl(var(--warning) / 0.7)",
          800: "hsl(var(--warning) / 0.8)",
          900: "hsl(var(--warning) / 0.9)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "fun-blue": {
          DEFAULT: "hsl(var(--fun-blue))",
          5: "hsl(var(--fun-blue) / 0.05)",
          8: "hsl(var(--fun-blue) / 0.08)",
          10: "hsl(var(--fun-blue) / 0.1)",
          12: "hsl(var(--fun-blue) / 0.12)",
          15: "hsl(var(--fun-blue) / 0.15)",
          16: "hsl(var(--fun-blue) / 0.16)",
          18: "hsl(var(--fun-blue) / 0.18)",
          20: "hsl(var(--fun-blue) / 0.2)",
          25: "hsl(var(--fun-blue) / 0.25)",
          30: "hsl(var(--fun-blue) / 0.3)",
          50: "hsl(var(--fun-blue) / 0.05)",
          100: "hsl(var(--fun-blue) / 0.1)",
          200: "hsl(var(--fun-blue) / 0.2)",
          300: "hsl(var(--fun-blue) / 0.3)",
          400: "hsl(var(--fun-blue) / 0.4)",
          500: "hsl(var(--fun-blue) / 0.5)",
          600: "hsl(var(--fun-blue) / 0.6)",
          700: "hsl(var(--fun-blue) / 0.7)",
          800: "hsl(var(--fun-blue) / 0.8)",
          900: "hsl(var(--fun-blue) / 0.9)",
        },
        "fun-purple": {
          DEFAULT: "hsl(var(--fun-purple))",
          5: "hsl(var(--fun-purple) / 0.05)",
          8: "hsl(var(--fun-purple) / 0.08)",
          10: "hsl(var(--fun-purple) / 0.1)",
          12: "hsl(var(--fun-purple) / 0.12)",
          15: "hsl(var(--fun-purple) / 0.15)",
          20: "hsl(var(--fun-purple) / 0.2)",
          25: "hsl(var(--fun-purple) / 0.25)",
          30: "hsl(var(--fun-purple) / 0.3)",
          50: "hsl(var(--fun-purple) / 0.05)",
          100: "hsl(var(--fun-purple) / 0.1)",
          200: "hsl(var(--fun-purple) / 0.2)",
          300: "hsl(var(--fun-purple) / 0.3)",
          400: "hsl(var(--fun-purple) / 0.4)",
          500: "hsl(var(--fun-purple) / 0.5)",
          600: "hsl(var(--fun-purple) / 0.6)",
          700: "hsl(var(--fun-purple) / 0.7)",
          800: "hsl(var(--fun-purple) / 0.8)",
          900: "hsl(var(--fun-purple) / 0.9)",
        },
        "fun-pink": {
          DEFAULT: "hsl(var(--fun-pink))",
          5: "hsl(var(--fun-pink) / 0.05)",
          8: "hsl(var(--fun-pink) / 0.08)",
          10: "hsl(var(--fun-pink) / 0.1)",
          12: "hsl(var(--fun-pink) / 0.12)",
          15: "hsl(var(--fun-pink) / 0.15)",
          18: "hsl(var(--fun-pink) / 0.18)",
          20: "hsl(var(--fun-pink) / 0.2)",
          25: "hsl(var(--fun-pink) / 0.25)",
          50: "hsl(var(--fun-pink) / 0.05)",
          100: "hsl(var(--fun-pink) / 0.1)",
          200: "hsl(var(--fun-pink) / 0.2)",
          300: "hsl(var(--fun-pink) / 0.3)",
          400: "hsl(var(--fun-pink) / 0.4)",
          500: "hsl(var(--fun-pink) / 0.5)",
          600: "hsl(var(--fun-pink) / 0.6)",
          700: "hsl(var(--fun-pink) / 0.7)",
          800: "hsl(var(--fun-pink) / 0.8)",
          900: "hsl(var(--fun-pink) / 0.9)",
        },
        "fun-orange": {
          DEFAULT: "hsl(var(--fun-orange))",
          5: "hsl(var(--fun-orange) / 0.05)",
          8: "hsl(var(--fun-orange) / 0.08)",
          10: "hsl(var(--fun-orange) / 0.1)",
          12: "hsl(var(--fun-orange) / 0.12)",
          15: "hsl(var(--fun-orange) / 0.15)",
          16: "hsl(var(--fun-orange) / 0.16)",
          18: "hsl(var(--fun-orange) / 0.18)",
          20: "hsl(var(--fun-orange) / 0.2)",
          25: "hsl(var(--fun-orange) / 0.25)",
          50: "hsl(var(--fun-orange) / 0.05)",
          100: "hsl(var(--fun-orange) / 0.1)",
          200: "hsl(var(--fun-orange) / 0.2)",
          300: "hsl(var(--fun-orange) / 0.3)",
          400: "hsl(var(--fun-orange) / 0.4)",
          500: "hsl(var(--fun-orange) / 0.5)",
          600: "hsl(var(--fun-orange) / 0.6)",
          700: "hsl(var(--fun-orange) / 0.7)",
          800: "hsl(var(--fun-orange) / 0.8)",
          900: "hsl(var(--fun-orange) / 0.9)",
        },
      },
      boxShadow: {
        eco: "var(--shadow-eco)",
        glow: "var(--shadow-glow)",
        card: "var(--shadow-card)",
        fun: "var(--shadow-fun)",
        magic: "var(--shadow-magic)",
        energy: "var(--shadow-energy)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
} satisfies Config;
